function model
% Livelink connection and model initialization
import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.component.create('comp1', false);
model.component('comp1').geom.create('geom1', 3);
model.component('comp1').defineLocalCoord(false);

% Set geometry and mesh generation parameters
boxLx = BOXLX;
boxLy = BOXLY;
boxLz = BOXLZ;

model.param.set('max_size_tri', '10.0');
model.param.set('min_size_tri', '0.5');
model.param.set('max_size_tet_in', '2.4');
model.param.set('min_size_tet_in', '0.5');
model.param.set('max_size_tet_out', '20.0');
model.param.set('min_size_tet_out', '0.5');

% Build geometry
model.component('comp1').view('view1').set('transparency',true);

model.component('comp1').geom('geom1').repairTolType('relative');
model.component('comp1').geom('geom1').create('blk1', 'Block');
model.component('comp1').geom('geom1').feature('blk1').set('base', 'center');
model.component('comp1').geom('geom1').feature('blk1').set('size', [boxLx boxLy boxLz]);
%----------------------------INSERT NANOPARTICLES HERE-----------------------------------------------%
%----------------------------------------------------------------------------------------------------%
%----------------------------INSERT GRAFTING POINTS HERE---------------------------------------------%
%----------------------------------------------------------------------------------------------------%
model.component('comp1').geom('geom1').create('dif1', 'Difference');
model.component('comp1').geom('geom1').feature('dif1').selection('input').set({'blk1'});
model.component('comp1').geom('geom1').feature('dif1').selection('input2').set({'sph1' 'sph2' 'sph3' 'sph4' 'sph5' 'sph6' 'sph7' 'sph8' 'sph9' 'sph10' 'sph11' 'sph12' 'sph13' 'sph14'});
model.component('comp1').geom('geom1').create('co1', 'Compose');
model.component('comp1').geom('geom1').feature('co1').selection('input').set({'dif1' 'sph15' 'sph16' 'sph17' 'sph18' 'sph19' 'sph20' 'sph21' 'sph22' 'sph23' 'sph24' 'sph25' 'sph26' 'sph27' 'sph28'});
model.component('comp1').geom('geom1').feature('co1').set('formula', 'dif1+dif1*(sph15+sph16+sph17+sph18+sph19+sph20+sph21+sph22+sph23+sph24+sph25+sph26+sph27+sph28)');
model.component('comp1').geom('geom1').feature('fin').set('repairtoltype', 'relative');
model.component('comp1').geom('geom1').create('ige1', 'IgnoreEdges');
model.component('comp1').geom('geom1').feature('ige1').selection('input').set('fin(1)', [22 25 27 29 31 33 34 35 63 65 68 70 75 77 80 82 85 87 89 91 93 94 95 97 99 101 103 104 105 106 107 108 109 110 115 116 117 118 119 120 131 132 133 134 145 146 147 148]);
model.component('comp1').geom('geom1').create('igv1', 'IgnoreVertices');
model.component('comp1').geom('geom1').feature('igv1').selection('input').set('ige1(1)', [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192]);
model.component('comp1').geom('geom1').run;

% Set physics parameters and boundary conditions
model.component('comp1').physics.create('c', 'CoefficientFormPDE', 'geom1');
model.component('comp1').physics('c').prop('ShapeProperty').set('order', 1);
model.component('comp1').physics('c').feature('cfeq1').set('f', 0);
model.component('comp1').physics('c').feature('init1').set('u', 1);
model.component('comp1').physics('c').create('dir1', 'DirichletBoundary', 2);
model.component('comp1').physics('c').feature('dir1').selection.set([3 10 17 24 25 37 38 39 40 54 55 56 57 58]);
model.component('comp1').physics('c').create('pc1', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc1').selection.set([13 14]);
model.component('comp1').physics('c').create('pc2', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc2').selection.set([5 27]);
model.component('comp1').physics('c').create('pc3', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc3').selection.set([4 60]);
model.component('comp1').physics('c').create('pc4', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc4').selection.set([32 34]);
model.component('comp1').physics('c').create('pc5', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc5').selection.set([29 36]);
model.component('comp1').physics('c').create('pc6', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc6').selection.set([15 62]);
model.component('comp1').physics('c').create('pc7', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc7').selection.set([1 59]);
model.component('comp1').physics('c').create('pc8', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc8').selection.set([7 61]);
model.component('comp1').physics('c').create('pc9', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc9').selection.set([21 64]);
model.component('comp1').physics('c').create('pc10', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc10').selection.set([18 63]);
model.component('comp1').physics('c').create('pc11', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc11').selection.set([8 28]);
model.component('comp1').physics('c').create('pc12', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc12').selection.set([44 52]);
model.component('comp1').physics('c').create('pc13', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc13').selection.set([41 49]);
model.component('comp1').physics('c').create('pc14', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc14').selection.set([2 26]);
model.component('comp1').physics('c').create('pc15', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc15').selection.set([11 12]);
model.component('comp1').physics('c').create('pc16', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc16').selection.set([42 45]);
model.component('comp1').physics('c').create('pc17', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc17').selection.set([19 22]);
model.component('comp1').physics('c').create('pc18', 'PeriodicCondition', 2);
model.component('comp1').physics('c').feature('pc18').selection.set([48 51]);

% Create mesh and set the parameters of its size
model.component('comp1').mesh.create('mesh1');
model.component('comp1').mesh('mesh1').create('ftri1', 'FreeTri');
model.component('comp1').mesh('mesh1').create('ftri2', 'FreeTri');
model.component('comp1').mesh('mesh1').create('ftri3', 'FreeTri');
model.component('comp1').mesh('mesh1').create('cpf1', 'CopyFace');
model.component('comp1').mesh('mesh1').create('cpf2', 'CopyFace');
model.component('comp1').mesh('mesh1').create('cpf3', 'CopyFace');
model.component('comp1').mesh('mesh1').create('ftri4', 'FreeTri');
model.component('comp1').mesh('mesh1').create('ftri5', 'FreeTri');
model.component('comp1').mesh('mesh1').create('ftri6', 'FreeTri');
model.component('comp1').mesh('mesh1').create('cpf4', 'CopyFace');
model.component('comp1').mesh('mesh1').create('cpf5', 'CopyFace');
model.component('comp1').mesh('mesh1').create('cpf6', 'CopyFace');
model.component('comp1').mesh('mesh1').create('ftri7', 'FreeTri');
model.component('comp1').mesh('mesh1').create('ftri8', 'FreeTri');
model.component('comp1').mesh('mesh1').create('ftri9', 'FreeTri');
model.component('comp1').mesh('mesh1').create('ftri10', 'FreeTri');
model.component('comp1').mesh('mesh1').create('cpf7', 'CopyFace');
model.component('comp1').mesh('mesh1').create('cpf8', 'CopyFace');
model.component('comp1').mesh('mesh1').create('cpf9', 'CopyFace');
model.component('comp1').mesh('mesh1').create('cpf10', 'CopyFace');
model.component('comp1').mesh('mesh1').create('ftri11', 'FreeTri');
model.component('comp1').mesh('mesh1').create('ftri12', 'FreeTri');
model.component('comp1').mesh('mesh1').create('ftri13', 'FreeTri');
model.component('comp1').mesh('mesh1').create('ftri14', 'FreeTri');
model.component('comp1').mesh('mesh1').create('cpf11', 'CopyFace');
model.component('comp1').mesh('mesh1').create('cpf12', 'CopyFace');
model.component('comp1').mesh('mesh1').create('cpf13', 'CopyFace');
model.component('comp1').mesh('mesh1').create('cpf14', 'CopyFace');
model.component('comp1').mesh('mesh1').create('ftri15', 'FreeTri');
model.component('comp1').mesh('mesh1').create('ftri16', 'FreeTri');
model.component('comp1').mesh('mesh1').create('ftri17', 'FreeTri');
model.component('comp1').mesh('mesh1').create('ftri18', 'FreeTri');
model.component('comp1').mesh('mesh1').create('cpf15', 'CopyFace');
model.component('comp1').mesh('mesh1').create('cpf16', 'CopyFace');
model.component('comp1').mesh('mesh1').create('cpf17', 'CopyFace');
model.component('comp1').mesh('mesh1').create('cpf18', 'CopyFace');
model.component('comp1').mesh('mesh1').create('ftri19', 'FreeTri');
model.component('comp1').mesh('mesh1').create('ftet1', 'FreeTet');
model.component('comp1').mesh('mesh1').create('ftet2', 'FreeTet');
model.component('comp1').mesh('mesh1').feature('ftri1').selection.set([5]);
model.component('comp1').mesh('mesh1').feature('ftri1').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').selection.geom('geom1');
model.component('comp1').mesh('mesh1').feature('ftri2').selection.set([13]);
model.component('comp1').mesh('mesh1').feature('ftri2').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri3').selection.set([60]);
model.component('comp1').mesh('mesh1').feature('ftri3').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri4').selection.set([36]);
model.component('comp1').mesh('mesh1').feature('ftri4').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri4').feature('size1').selection.geom('geom1');
model.component('comp1').mesh('mesh1').feature('ftri5').selection.set([32]);
model.component('comp1').mesh('mesh1').feature('ftri5').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri5').feature('size1').selection.geom('geom1');
model.component('comp1').mesh('mesh1').feature('ftri6').selection.set([62]);
model.component('comp1').mesh('mesh1').feature('ftri6').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri6').feature('size1').selection.geom('geom1');
model.component('comp1').mesh('mesh1').feature('ftri7').selection.set([7]);
model.component('comp1').mesh('mesh1').feature('ftri7').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri7').feature('size1').selection.geom('geom1');
model.component('comp1').mesh('mesh1').feature('ftri8').selection.set([21]);
model.component('comp1').mesh('mesh1').feature('ftri8').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri8').feature('size1').selection.geom('geom1');
model.component('comp1').mesh('mesh1').feature('ftri9').selection.set([1]);
model.component('comp1').mesh('mesh1').feature('ftri9').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri9').feature('size1').selection.geom('geom1');
model.component('comp1').mesh('mesh1').feature('ftri10').selection.set([18]);
model.component('comp1').mesh('mesh1').feature('ftri10').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri10').feature('size1').selection.geom('geom1');
model.component('comp1').mesh('mesh1').feature('ftri11').selection.set([8]);
model.component('comp1').mesh('mesh1').feature('ftri11').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri11').feature('size1').selection.geom('geom1');
model.component('comp1').mesh('mesh1').feature('ftri12').selection.set([44]);
model.component('comp1').mesh('mesh1').feature('ftri12').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri12').feature('size1').selection.geom('geom1');
model.component('comp1').mesh('mesh1').feature('ftri13').selection.set([2]);
model.component('comp1').mesh('mesh1').feature('ftri13').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri13').feature('size1').selection.geom('geom1');
model.component('comp1').mesh('mesh1').feature('ftri14').selection.set([41]);
model.component('comp1').mesh('mesh1').feature('ftri14').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri14').feature('size1').selection.geom('geom1');
model.component('comp1').mesh('mesh1').feature('ftri15').selection.set([11]);
model.component('comp1').mesh('mesh1').feature('ftri15').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri15').feature('size1').selection.geom('geom1');
model.component('comp1').mesh('mesh1').feature('ftri16').selection.set([42]);
model.component('comp1').mesh('mesh1').feature('ftri16').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri16').feature('size1').selection.geom('geom1');
model.component('comp1').mesh('mesh1').feature('ftri17').selection.set([19]);
model.component('comp1').mesh('mesh1').feature('ftri17').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri17').feature('size1').selection.geom('geom1');
model.component('comp1').mesh('mesh1').feature('ftri18').selection.set([48]);
model.component('comp1').mesh('mesh1').feature('ftri18').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri18').feature('size1').selection.geom('geom1');
model.component('comp1').mesh('mesh1').feature('ftri19').selection.set([6 9 16 20 23 30 31 33 35 43 46 47 50 53]);
model.component('comp1').mesh('mesh1').feature('ftri19').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri19').feature('size1').selection.geom('geom1');
model.component('comp1').mesh('mesh1').feature('ftet1').selection.geom('geom1', 3);
model.component('comp1').mesh('mesh1').feature('ftet1').selection.set([1 3 4 5 6 7 8 9 10 11 12 13 14 15]);
model.component('comp1').mesh('mesh1').feature('ftet1').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftet2').selection.geom('geom1', 3);
model.component('comp1').mesh('mesh1').feature('ftet2').selection.set([2]);
model.component('comp1').mesh('mesh1').feature('ftet2').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftet2').feature('size1').selection.set([1 3 4 5 6 7 8 9 10 11 12 13 14 15]);

model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('ftri2').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri2').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri2').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri2').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri2').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri2').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri2').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri2').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri2').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri2').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri2').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('ftri3').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri3').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri3').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri3').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri3').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri3').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri3').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri3').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri3').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri3').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri3').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('cpf1').selection('source').set([5]);
model.component('comp1').mesh('mesh1').feature('cpf1').selection('destination').set([27]);
model.component('comp1').mesh('mesh1').feature('cpf2').selection('source').set([13]);
model.component('comp1').mesh('mesh1').feature('cpf2').selection('destination').set([14]);
model.component('comp1').mesh('mesh1').feature('cpf3').selection('source').set([60]);
model.component('comp1').mesh('mesh1').feature('cpf3').selection('destination').set([4]);
model.component('comp1').mesh('mesh1').feature('ftri4').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri4').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri4').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri4').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri4').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri4').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri4').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri4').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri4').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri4').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri4').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('ftri5').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri5').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri5').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri5').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri5').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri5').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri5').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri5').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri5').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri5').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri5').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('ftri6').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri6').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri6').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri6').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri6').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri6').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri6').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri6').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri6').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri6').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri6').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('cpf4').selection('source').set([62]);
model.component('comp1').mesh('mesh1').feature('cpf4').selection('destination').set([15]);
model.component('comp1').mesh('mesh1').feature('cpf5').selection('source').set([36]);
model.component('comp1').mesh('mesh1').feature('cpf5').selection('destination').set([29]);
model.component('comp1').mesh('mesh1').feature('cpf6').selection('source').set([32]);
model.component('comp1').mesh('mesh1').feature('cpf6').selection('destination').set([34]);
model.component('comp1').mesh('mesh1').feature('ftri7').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri7').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri7').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri7').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri7').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri7').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri7').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri7').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri7').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri7').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri7').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('ftri8').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri8').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri8').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri8').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri8').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri8').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri8').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri8').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri8').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri8').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri8').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('ftri9').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri9').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri9').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri9').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri9').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri9').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri9').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri9').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri9').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri9').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri9').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('ftri10').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri10').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri10').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri10').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri10').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri10').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri10').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri10').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri10').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri10').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri10').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('cpf7').selection('source').set([7]);
model.component('comp1').mesh('mesh1').feature('cpf7').selection('destination').set([61]);
model.component('comp1').mesh('mesh1').feature('cpf8').selection('source').set([21]);
model.component('comp1').mesh('mesh1').feature('cpf8').selection('destination').set([64]);
model.component('comp1').mesh('mesh1').feature('cpf9').selection('source').set([1]);
model.component('comp1').mesh('mesh1').feature('cpf9').selection('destination').set([59]);
model.component('comp1').mesh('mesh1').feature('cpf10').selection('source').set([18]);
model.component('comp1').mesh('mesh1').feature('cpf10').selection('destination').set([63]);
model.component('comp1').mesh('mesh1').feature('ftri11').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri11').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri11').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri11').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri11').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri11').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri11').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri11').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri11').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri11').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri11').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('ftri12').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri12').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri12').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri12').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri12').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri12').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri12').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri12').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri12').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri12').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri12').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('ftri13').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri13').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri13').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri13').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri13').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri13').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri13').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri13').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri13').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri13').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri13').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('ftri14').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri14').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri14').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri14').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri14').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri14').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri14').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri14').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri14').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri14').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri14').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('cpf11').selection('source').set([8]);
model.component('comp1').mesh('mesh1').feature('cpf11').selection('destination').set([28]);
model.component('comp1').mesh('mesh1').feature('cpf12').selection('source').set([44]);
model.component('comp1').mesh('mesh1').feature('cpf12').selection('destination').set([52]);
model.component('comp1').mesh('mesh1').feature('cpf13').selection('source').set([2]);
model.component('comp1').mesh('mesh1').feature('cpf13').selection('destination').set([26]);
model.component('comp1').mesh('mesh1').feature('cpf14').selection('source').set([41]);
model.component('comp1').mesh('mesh1').feature('cpf14').selection('destination').set([49]);
model.component('comp1').mesh('mesh1').feature('ftri15').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri15').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri15').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri15').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri15').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri15').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri15').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri15').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri15').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri15').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri15').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('ftri16').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri16').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri16').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri16').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri16').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri16').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri16').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri16').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri16').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri16').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri16').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('ftri17').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri17').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri17').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri17').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri17').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri17').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri17').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri17').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri17').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri17').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri17').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('ftri18').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri18').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri18').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri18').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri18').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri18').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri18').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri18').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri18').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri18').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri18').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('cpf15').selection('source').set([11]);
model.component('comp1').mesh('mesh1').feature('cpf15').selection('destination').set([12]);
model.component('comp1').mesh('mesh1').feature('cpf16').selection('source').set([42]);
model.component('comp1').mesh('mesh1').feature('cpf16').selection('destination').set([45]);
model.component('comp1').mesh('mesh1').feature('cpf17').selection('source').set([48]);
model.component('comp1').mesh('mesh1').feature('cpf17').selection('destination').set([51]);
model.component('comp1').mesh('mesh1').feature('cpf18').selection('source').set([19]);
model.component('comp1').mesh('mesh1').feature('cpf18').selection('destination').set([22]);
model.component('comp1').mesh('mesh1').feature('ftri19').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri19').feature('size1').set('hmax', 'max_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri19').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftri19').feature('size1').set('hmin', 'min_size_tri');
model.component('comp1').mesh('mesh1').feature('ftri19').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftri19').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftri19').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftri19').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftri19').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri19').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftri19').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hmax', 'max_size_tet_in');
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hmin', 'min_size_tet_in');
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftet1').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').feature('ftet2').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftet2').feature('size1').set('hmax', 'max_size_tet_out');
model.component('comp1').mesh('mesh1').feature('ftet2').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('ftet2').feature('size1').set('hmin', 'min_size_tet_out');
model.component('comp1').mesh('mesh1').feature('ftet2').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('ftet2').feature('size1').set('hcurve', 0.3);
model.component('comp1').mesh('mesh1').feature('ftet2').feature('size1').set('hcurveactive', true);
model.component('comp1').mesh('mesh1').feature('ftet2').feature('size1').set('hnarrow', 0.85);
model.component('comp1').mesh('mesh1').feature('ftet2').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftet2').feature('size1').set('hgrad', 1.35);
model.component('comp1').mesh('mesh1').feature('ftet2').feature('size1').set('hgradactive', true);
model.component('comp1').mesh('mesh1').run;

% Solve the model
model.study.create('std1');
model.study('std1').create('time', 'Transient');
model.study('std1').feature('time').set('tlist', 'range(0,0.2,1)');

model.sol.create('sol1');
model.sol('sol1').study('std1');
model.sol('sol1').attach('std1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').create('t1', 'Time');
model.sol('sol1').feature('t1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('t1').feature.remove('fcDef');
model.sol('sol1').feature('v1').set('clist', {'range(0,0.2,1)' '0.001[s]'});
model.sol('sol1').feature('t1').set('tlist', 'range(0,0.2,1)');
model.sol('sol1').runAll;

% Export mesh in ascii format
model.result.export.create('mesh1', 'Mesh');
model.result.export('mesh1').set('type3D', 'mphascii');
model.result.export('mesh1').set('filename', 'in.mesh.mphtxt');
model.result.export('mesh1').run;

% Save model in comsol mph format
DIR = './';
FF  = 'model';

filename = strcat(FF,'.mph');
file     = strcat(DIR,filename);
model.save(file);
